export const FETCH_CLOUDINARY_IMAGES = 'FETCH_CLOUDINARY_IMAGES';
export const FETCH_CLOUDINARY_IMAGES_SUCCESS = 'FETCH_CLOUDINARY_IMAGES_SUCCESS';
export const FETCH_CLOUDINARY_IMAGES_ERROR = 'FETCH_CLOUDINARY_IMAGES_ERROR';
export const FETCH_CLOUDINARY_VIDEOS = 'FETCH_CLOUDINARY_VIDEOS';
export const FETCH_CLOUDINARY_VIDEOS_SUCCESS = 'FETCH_CLOUDINARY_VIDEOS_SUCCESS';
export const FETCH_CLOUDINARY_VIDEOS_ERROR = 'FETCH_CLOUDINARY_VIDEOS_ERROR';
export const SET_TAG_FILTER = 'SET_TAG_FILTER';
